<?php
$struct = array(
	'action' => array(
		'index.php',
		'login.php',
		'logout.php',
		'profile.php',
		'home.php',
		'option.php',
		'user.php',
		'customer.php',
        'company.php',
		'report.php',
		'forgot.php'
	),
	'include' => array(
		'mysql.php',
		'mysqlii.php',
		'database.php',
		'index.php',
		'option.php',
		'passwordhash.php',
		'jsmin.php',
		'url.php',
		'xtemplate.php',
		'htmlmin.php',
		'bootstrap.php',
		'auth.php'
	),
	'model' => array(
		'user.php',
		'report.php',
		'customer.php',
        'company.php'
	),
	'uploads' => array('index.php'),
	'backups' => array('index.php','database.sql'),
	'template' => array(
		'css' => array('index.php'),
		'js' => array('index.php'),
		'style.css',
		'index.php',
		'header.php',
		'footer.php',
		'navigation.php',
		'login.php',
		'option.php',
        'frm-option.php',
		'user.php',
		'frm-user.php',
		'customer.php',
		'frm-customer.php',
		'report.php',
		'frm-report.php',
        'company.php',
        'frm-company.php',
		'forgot.php',
		'profile.php'
	),
	'init.php',
	'config.php',
	'index.php',
	'ajax.php',
	'service.php',
    'favicon.png'
);